version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: pub
    directory: "/mobile"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: gradle
    directory: "/mobile/android"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
